
'use client';

import { useState, useEffect } from 'react';
import { useAuth } from '@/contexts/auth-context';
import { useRouter } from 'next/navigation';
import { collection, query, where, onSnapshot, Timestamp } from 'firebase/firestore';
import { db } from '@/lib/firebase';
import { AppHeader } from '@/components/app-header';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { Skeleton } from '@/components/ui/skeleton';
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '@/components/ui/card';
import { Facebook, Twitter, Instagram, WandSparkles, ClipboardList, BarChart3, Quote, CheckCircle2 } from 'lucide-react';
import type { Routine as AthleteRoutine } from '@/components/athlete-routine-list';
import { AthleteRoutineList } from '@/components/athlete-routine-list';
import { AthleteNav } from '@/components/athlete-nav';
import Image from 'next/image';
import { cn } from '@/lib/utils';
import { AppDashboardIllustration } from '@/components/ui/app-dashboard-illustration';


function AthleteDashboard() {
    const { user } = useAuth();
    const [routines, setRoutines] = useState<AthleteRoutine[]>([]);
    const [isLoading, setIsLoading] = useState(true);

    useEffect(() => {
        if (!user) return;

        setIsLoading(true);
        const routinesQuery = query(
            collection(db, 'routines'),
            where('athleteId', '==', user.uid)
        );

        const unsubscribe = onSnapshot(routinesQuery, (snapshot) => {
            const fetchedRoutines = snapshot.docs.map(doc => {
                const data = doc.data();
                return {
                    id: doc.id,
                    routineName: data.routineName,
                    routineTypeName: data.routineTypeName,
                    routineDate: (data.routineDate as Timestamp).toDate(),
                    blocks: data.blocks,
                    coachId: data.coachId,
                    progress: data.progress,
                } as AthleteRoutine;
            }).sort((a, b) => b.routineDate.getTime() - a.routineDate.getTime());
            setRoutines(fetchedRoutines);
            setIsLoading(false);
        }, (error) => {
            console.error("Error fetching routines: ", error);
            setIsLoading(false);
        });

        return () => unsubscribe();
    }, [user]);

    return (
        <div className="w-full max-w-4xl space-y-8">
            <AthleteNav />
            {isLoading ? (
                <div className="space-y-4">
                    <Skeleton className="h-20 w-full" />
                    <Skeleton className="h-20 w-full" />
                    <Skeleton className="h-20 w-full" />
                </div>
            ) : (
                <AthleteRoutineList routines={routines} />
            )}
        </div>
    );
}

function GuestLandingPage() {
  const socialLinks = [
    { href: "#", icon: Facebook, name: "Facebook" },
    { href: "#", icon: Twitter, name: "Twitter" },
    { href: "#", icon: Instagram, name: "Instagram" },
  ];

  const features = [
    {
      icon: WandSparkles,
      title: "AI-Powered Plans",
      description: "Get personalized workout routines generated by our advanced AI, tailored to your goals and fitness level.",
    },
    {
      icon: ClipboardList,
      title: "Expert Coaching Tools",
      description: "For coaches and gym owners, a powerful suite of tools to create, assign, and manage client routines.",
    },
    {
      icon: BarChart3,
      title: "Track Your Progress",
      description: "Log every set and watch your strength grow with detailed stats and beautiful charts.",
    },
  ];

  const testimonials = [
    {
      quote: "Fitness Flow revolutionized how I train my clients. The routine creator is a game-changer and saves me hours every week.",
      name: "Alex R.",
      role: "Head Coach, Velocity Gym",
    },
    {
      quote: "As an athlete, having my workouts on my phone and tracking my progress so easily has been incredibly motivating. The AI generator is brilliant for my off-days!",
      name: "Samantha B.",
      role: "Athlete",
    },
  ];

  return (
    <div className="w-full bg-gray-950 text-white">
      {/* Hero Section */}
      <div className="relative">
        <div className="absolute inset-0">
          <Image
            src="/hero-background.jpg"
            alt="Fitness motivation"
            fill
            className="object-cover opacity-40"
            data-ai-hint="muscular man fitness"
            priority
          />
          <div className="absolute inset-0 bg-gradient-to-r from-gray-950 via-gray-950/80 to-transparent" />
        </div>
        <div className="relative z-10 min-h-screen flex flex-col">
          <header className="py-6 px-4 sm:px-6 lg:px-8">
            <div className="max-w-7xl mx-auto flex justify-between items-center">
              <Link href="/" className="text-2xl font-bold text-white tracking-wider">
                FITNESS FLOW
              </Link>
              <nav className="hidden md:flex items-center space-x-6 text-sm font-medium">
                <Link href="#" className="text-white transition hover:text-blue-400">Features</Link>
                <Link href="#" className="text-white transition hover:text-blue-400">About</Link>
                <Link href="#" className="text-white transition hover:text-blue-400">Contact</Link>
              </nav>
              <div>
                <Button asChild variant="outline" className="border-white/50 bg-transparent text-white hover:bg-white hover:text-gray-950">
                  <Link href="/login">Login</Link>
                </Button>
              </div>
            </div>
          </header>
          <main className="flex-grow flex items-center py-16 sm:py-24">
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
              <div className="max-w-xl">
                <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold text-white leading-tight tracking-tight animate-fade-in">
                  Build Perfect Body
                  <br />
                  With Clean Mind
                </h1>
                <p className="mt-6 text-lg text-gray-300 animate-fade-in [animation-delay:200ms]">
                  Unleash your potential with AI-powered workout plans, expert coaching tools, and seamless progress tracking. Join the community dedicated to achieving peak fitness.
                </p>
                <div className="mt-8 animate-fade-in [animation-delay:400ms]">
                  <Button asChild size="lg" className="bg-blue-600 text-white hover:bg-blue-700 px-10 py-6 text-base font-bold">
                    <Link href="/signup">Get Started</Link>
                  </Button>
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
      
      {/* Features Section */}
      <section className="py-20 bg-gray-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-white">Everything You Need to Succeed</h2>
            <p className="mt-4 text-lg text-gray-400">The most advanced and intuitive fitness platform.</p>
          </div>
          <div className="mt-16 grid md:grid-cols-3 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-gray-950/50 p-8 rounded-lg text-center animate-fade-in" style={{ animationDelay: `${index * 150}ms`}}>
                <div className="flex justify-center items-center h-16 w-16 bg-blue-600/20 text-blue-400 rounded-lg mx-auto">
                  <feature.icon className="h-8 w-8" />
                </div>
                <h3 className="mt-6 text-xl font-bold text-white">{feature.title}</h3>
                <p className="mt-2 text-base text-gray-400">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Why Choose Us Section */}
      <section className="py-20 bg-gray-950">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-2 gap-12 items-center">
          <div className="animate-fade-in">
            <h2 className="text-3xl font-extrabold text-white">A Smarter Way to Train</h2>
            <p className="mt-4 text-lg text-gray-400">Stop guessing, start progressing. Fitness Flow provides the structure and data you need to reach your goals faster. Whether you're a coach managing a team or an athlete striving for a new personal best, our platform is built for you.</p>
            <ul className="mt-6 space-y-4 text-gray-300">
              <li className="flex items-start gap-3"><CheckCircle2 className="h-6 w-6 text-blue-500 mt-1 shrink-0" /><span><strong>Data-Driven Decisions:</strong> Visualize your progress and make informed adjustments to your training.</span></li>
              <li className="flex items-start gap-3"><CheckCircle2 className="h-6 w-6 text-blue-500 mt-1 shrink-0" /><span><strong>Seamless Experience:</strong> From the gym owner to the athlete, enjoy a user-friendly interface that just works.</span></li>
              <li className="flex items-start gap-3"><CheckCircle2 className="h-6 w-6 text-blue-500 mt-1 shrink-0" /><span><strong>Motivation Built-In:</strong> Track your achievements and stay consistent with a platform that grows with you.</span></li>
            </ul>
          </div>
          <div className="animate-fade-in [animation-delay:200ms]">
            <AppDashboardIllustration />
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-20 bg-gray-900">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-extrabold text-white">Trusted by Top Coaches and Athletes</h2>
          </div>
          <div className="mt-16 grid md:grid-cols-2 gap-8">
            {testimonials.map((testimonial, index) => (
              <Card key={index} className="bg-gray-950/50 border-gray-800 text-white p-8">
                <CardContent className="p-0">
                  <Quote className="h-8 w-8 text-blue-500 mb-4" />
                  <p className="text-lg text-gray-300">"{testimonial.quote}"</p>
                  <div className="flex items-center gap-4 mt-6">
                    <div className="flex-shrink-0">
                      <svg
                        className="h-12 w-12 rounded-full bg-gray-800 p-2 text-gray-500"
                        fill="none"
                        stroke="currentColor"
                        viewBox="0 0 24 24"
                        xmlns="http://www.w3.org/2000/svg"
                        strokeWidth="1.5"
                      >
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                        <circle cx="12" cy="7" r="4"></circle>
                      </svg>
                    </div>
                    <div>
                      <p className="font-bold">{testimonial.name}</p>
                      <p className="text-sm text-gray-400">{testimonial.role}</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA Section */}
      <section className="py-24 bg-gray-950">
        <div className="max-w-4xl mx-auto text-center px-4">
          <h2 className="text-4xl font-extrabold text-white">Ready to Unlock Your Potential?</h2>
          <p className="mt-4 text-xl text-gray-400">Join Fitness Flow today and take the first step towards a stronger, healthier you. Your peak performance awaits.</p>
          <div className="mt-8">
             <Button asChild size="lg" className="bg-blue-600 text-white hover:bg-blue-700 px-12 py-7 text-lg font-bold">
                <Link href="/signup">Sign Up for Free</Link>
             </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 border-t border-gray-800">
        <div className="max-w-7xl mx-auto py-12 px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row justify-between items-center gap-8">
            <div>
              <p className="text-lg font-bold tracking-wider">FITNESS FLOW</p>
              <p className="mt-2 text-sm text-gray-400">&copy; {new Date().getFullYear()} Fitness Flow. All Rights Reserved.</p>
            </div>
            <div className="flex space-x-6">
                {socialLinks.map((link) => (
                    <Link key={link.name} href={link.href} className="text-gray-400 hover:text-white">
                      <span className="sr-only">{link.name}</span>
                      <link.icon className="h-6 w-6" />
                    </Link>
                  ))}
            </div>
        </div>
      </footer>
    </div>
  );
}


export default function Home() {
    const { user, userProfile, loading } = useAuth();
    const router = useRouter();

    useEffect(() => {
        if (loading) return;

        if (user) {
            if (!userProfile?.gymId) {
                router.push('/create-gym');
            } else if (userProfile.role === 'gym-admin') {
                router.push('/admin');
            } else if (userProfile.role === 'coach') {
                router.push('/coach');
            }
        }
    }, [user, userProfile, loading, router]);

    if (loading) {
        return (
            <div className="flex flex-col min-h-screen items-center p-4 sm:p-8">
                <div className="w-full max-w-5xl flex items-center justify-between mb-10">
                    <Skeleton className="h-12 w-48" />
                    <Skeleton className="h-10 w-24" />
                </div>
                <div className="w-full max-w-2xl space-y-4">
                    <Skeleton className="h-48 w-full" />
                    <Skeleton className="h-12 w-1/3" />
                    <Skeleton className="h-64 w-full" />
                </div>
            </div>
        );
    }

    if (!user) {
        return <GuestLandingPage />;
    }

    if (userProfile?.role === 'gym-admin' || userProfile?.role === 'coach' || !userProfile?.gymId) {
        return (
            <div className="flex items-center justify-center min-h-screen">
                <p>Redirecting to your dashboard...</p>
            </div>
        );
    }
    
    const renderDashboardContent = () => {
        switch (userProfile.role) {
            case 'athlete':
                return <AthleteDashboard />;
            default:
                return (
                    <div className="w-full max-w-2xl text-center">
                        <Card className="p-8">
                            <CardHeader>
                                <CardTitle className="text-3xl font-headline">Welcome!</CardTitle>
                                <CardDescription>Your account is pending configuration by your gym administrator.</CardDescription>
                            </CardHeader>
                        </Card>
                    </div>
                );
        }
    };
    
    const isAthlete = userProfile.role === 'athlete';

    return (
        <div className={cn("flex flex-col min-h-screen", isAthlete && "pb-16 md:pb-0")}>
            <main className="flex-grow flex flex-col items-center p-4 sm:p-8">
                <AppHeader />
                <div className="flex-grow flex items-center justify-center w-full">
                    {renderDashboardContent()}
                </div>
            </main>
            <footer className="w-full text-center p-4 text-muted-foreground text-sm">
                <p>
                    Create your own routines, track your progress, and crush your goals.
                </p>
                <p>&copy; {new Date().getFullYear()} Fitness Flow. All Rights Reserved.</p>
            </footer>
        </div>
    );
}
