'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Dumbbell } from 'lucide-react';
import type { GenerateWorkoutRoutineOutput } from '@/ai/flows/generate-workout-routine';

type WorkoutDisplayProps = {
  routine: GenerateWorkoutRoutineOutput | null;
};

const formatRoutine = (text: string) => {
  const lines = text.split('\n').filter(line => line.trim().length > 0);
  
  return lines.map((line, index) => {
    line = line.trim();
    if (line.match(/^\*\*.+\*\*$/)) {
      return <h3 key={index} className="text-xl font-bold font-headline mt-6 mb-3 text-primary">{line.replace(/\*\*/g, '')}</h3>;
    }
    if (line.match(/^\*.+\*$/)) {
        return <h4 key={index} className="text-lg font-semibold font-headline mt-4 mb-2">{line.replace(/\*/g, '')}</h4>;
    }
    if (line.startsWith('- ') || line.startsWith('* ')) {
      return <li key={index} className="ml-5 list-disc mb-1">{line.substring(2)}</li>;
    }
    if (line.match(/^\d+\.\s/)) {
        return <li key={index} className="ml-5 list-decimal mb-1">{line.replace(/^\d+\.\s/, '')}</li>;
    }
    return <p key={index} className="mb-2">{line}</p>;
  });
};

export function WorkoutDisplay({ routine }: WorkoutDisplayProps) {
  if (!routine || !routine.routine) {
    return null;
  }

  return (
    <Card className="w-full max-w-2xl mx-auto mt-8 shadow-lg animate-fade-in">
      <CardHeader>
        <div className="flex items-center gap-3">
          <Dumbbell className="w-8 h-8 text-primary" />
          <div>
            <CardTitle className="font-headline text-2xl">Your New Workout Routine</CardTitle>
            <CardDescription>Here is the personalized routine generated by our AI.</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-2">
            {formatRoutine(routine.routine)}
        </div>
      </CardContent>
    </Card>
  );
}
